import time

def printer():
    print("           --  ")
    print("          /oo\\ ")
    print("      |  /    \\")
    print("      ---|    |")
    print("      |  |    |")
    print("      |  ......")
    time.sleep(2)
    print("           --  ")
    print("          /oo\\ ")
    print("       | /    \\")
    print("       --|    |")
    print("       | |    |")
    print("       | ......")
    time.sleep(2)
    print("           --  ")
    print("          /oo\\ ")
    print("        |/    \\")
    print("        -|    |")
    print("        ||    |")
    print("        |......")
    time.sleep(2)
    print("           --  ")
    print("          /oo\\ ")
    print("         /    \\")
    print("         |    |")
    print("         |    |")
    print("         ......")
    time.sleep(2)
    print("         -----   ")
    print("        / o o \\ ")
    print("       /       \\")
    print("       |       | ")
    print("       |       | ")
    time.sleep(2)
    print("         -----   ")
    print("        / o o \\ ")
    print("     --/       \\")
    print("    /   __|_|___ ")
    print("   /   |        |")
    print("   \\   |        |")
    print("    \\  |        |")
    time.sleep(2)

def maggie():
    print("      //\\\\//\\\\   ")
    print("     // //\\/ /\\    ")
    print("    /\\ / Q Q \\\\\\  ")
    print("   /\\ \\\\  _  / \\ ")
    print("    / / \\___/\\ /    ")
    print("    \\/\\ / /\\ /\\\\ ")
    print("    / /\\\\/\\ \\ /\\  ")
    print("")

printer()
maggie()
